export const ADD_BOOKMARK_REQUESTED = 'documents/ADD_BOOKMARK_REQUESTED'
export const ADD_BOOKMARK_SUCCESS = 'documents/ADD_BOOKMARK_SUCCESS'
export const ADD_BOOKMARK_FAILURE = 'documents/ADD_BOOKMARK_FAILURE'

export const REMOVE_BOOKMARK_REQUESTED = 'documents/REMOVE_BOOKMARK_REQUESTED'
export const REMOVE_BOOKMARK_SUCCESS = 'documents/REMOVE_BOOKMARK_SUCCESS'
export const REMOVE_BOOKMARK_FAILURE = 'documents/REMOVE_BOOKMARK_FAILURE'

export const DOCUMENT_REQUEST_SUBMITTED = 'documents/DOCUMENT_REQUEST_SUBMITTED'
export const DOCUMENT_REQUEST_SUCCESS = 'documents/DOCUMENT_REQUEST_SUCCESS'
export const DOCUMENT_REQUEST_FAILURE = 'documents/DOCUMENT_REQUEST_FAILURE'